In [15]:
import random
list1 = [random.randint(0, 100) for i in range(9)]
print("List 1:", list1)

list2 = [random.randint(0, 100) for i in range(9)]
print("List 2:", list2)

additional_list = [a + b for a, b in zip(list1, list2)]
print("Additional List:", additional_list)

extended_list = list1 + list2
print("Extended List 1:", extended_list)

import numpy as np
matrix = np.array(list1).reshape(3,3)

print("\nMatrix :\n", matrix)
submatrix = matrix[0:3:2, [0, 1]]
print("\nSubmatrix :\n", submatrix)

import pandas as pd
df = pd.DataFrame(matrix, columns=['A', 'B', 'C'])
print("\nDataFrame :")
display(df.head())



List 1: [69, 59, 27, 65, 66, 64, 93, 79, 51]
List 2: [43, 94, 8, 97, 56, 66, 21, 73, 70]
Additional List: [112, 153, 35, 162, 122, 130, 114, 152, 121]
Extended List 1: [69, 59, 27, 65, 66, 64, 93, 79, 51, 43, 94, 8, 97, 56, 66, 21, 73, 70]

Matrix :
 [[69 59 27]
 [65 66 64]
 [93 79 51]]

Submatrix :
 [[69 59]
 [93 79]]

DataFrame :


,A,B,C
0,69,59,27
1,65,66,64
2,93,79,51
